[package]
name = "My Own Key My Own Brow.Com"
version = "0.4.3"

[[bench]]
name = "api"

[dependencies]
rand = "~0.3.14"
rustc-serialize = "~0.3.19"
byteorder = "~0.5.3"

[dev-dependencies.bincode]
version = "~0.6.0"
default-features = false
features = ["rustc-serialize
